name: CI

on:
    push:
        branches: ["**"]
    pull_request:
        branches: ["**"]

jobs:
    build:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:latest
                env:
                    POSTGRES_DB: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_USER: postgres
                ports:
                    - 5432:5432
                # Set health checks to wait until postgres has started
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        strategy:
            fail-fast: false

            matrix:
                node-version: [20.x]
                node_index: [0, 1, 2, 3]
                total_nodes: [4]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            # - name: Install lsb-core
            #   run: sudo apt-get install lsb-core
            - run: npm ci
            - run: npm run build --if-present
            - run: npm test --if-present
              env:
                  CI_NODE_INDEX: ${{ matrix.node_index }}
                  CI_NODE_TOTAL: ${{ matrix.total_nodes }}
